# Generated by Django 2.0 on 2018-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Task_name',
            field=models.CharField(default='', max_length=15, verbose_name='任务名'),
        ),
    ]
