# Generated by Django 2.0 on 2018-05-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20180517_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_excel_last',
            field=models.CharField(default='', max_length=100, verbose_name='用户操作后的数据源'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_excel_origin',
            field=models.FileField(upload_to='personaldata', verbose_name='上传的初始数据源'),
        ),
    ]
