# Generated by Django 2.0 on 2018-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20180517_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Task_Folder',
            field=models.CharField(default='', max_length=50, verbose_name='文件夹路径'),
        ),
        migrations.AddField(
            model_name='task',
            name='Task_Folder_name',
            field=models.CharField(default='', max_length=50, verbose_name='文件夹名'),
        ),
        migrations.AddField(
            model_name='task',
            name='Task_Home',
            field=models.CharField(default='', max_length=2, verbose_name='任务存放盘'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_ID',
            field=models.IntegerField(default='', verbose_name='task_id'),
        ),
    ]
