# Generated by Django 2.0 on 2018-05-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataResources', '0001_initial'),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataresource',
            name='DataResources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_operation.UserAddData', verbose_name='数据源'),
        ),
    ]
