# Generated by Django 2.0 on 2018-05-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataResources', '0002_dataresource_dataresources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataresource',
            options={'verbose_name': '数据源', 'verbose_name_plural': '数据源'},
        ),
    ]
