# Generated by Django 2.0 on 2018-06-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20180604_1409'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataResources', '0003_auto_20180508_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataresource',
            name='DataResources',
        ),
        migrations.RemoveField(
            model_name='dataresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dataresource',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='dataresource',
            name='name',
        ),
        migrations.AddField(
            model_name='dataresource',
            name='Task_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Task.Task', verbose_name='任务编号'),
        ),
        migrations.AddField(
            model_name='dataresource',
            name='step1',
            field=models.CharField(default='', max_length=100, verbose_name='源文件名'),
        ),
        migrations.AddField(
            model_name='dataresource',
            name='step2',
            field=models.CharField(default='', max_length=100, verbose_name='源json文件'),
        ),
        migrations.AddField(
            model_name='dataresource',
            name='step3',
            field=models.CharField(default='', max_length=100, verbose_name='step3文件'),
        ),
        migrations.AddField(
            model_name='dataresource',
            name='step4',
            field=models.CharField(default='', max_length=100, verbose_name='step4文件'),
        ),
        migrations.AddField(
            model_name='dataresource',
            name='step5',
            field=models.CharField(default='', max_length=100, verbose_name='step5文件'),
        ),
        migrations.AddField(
            model_name='dataresource',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
