# Generated by Django 2.0 on 2018-05-08 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataResource', models.FileField(upload_to='personaldata', verbose_name='上传的数据源')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户添加数据源',
                'verbose_name_plural': '用户添加数据源',
            },
        ),
    ]
