# Generated by Django 2.0 on 2018-05-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_useradddata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradddata',
            name='Add_id',
            field=models.CharField(default='1', max_length=10, verbose_name='ID'),
        ),
    ]
