# Generated by Django 2.0 on 2018-05-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_useradddata_add_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradddata',
            name='Add_id',
        ),
    ]
